# Generated by Django 2.0 on 2018-11-12 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fixture', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operation',
            old_name='endTime',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='operation',
            old_name='startTime',
            new_name='start_time',
        ),
    ]
