# Generated by Django 2.0 on 2018-11-15 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixture', '0002_auto_20181112_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='type',
            field=models.CharField(choices=[('temperature', 'temperature'), ('pressure', 'pressure')], max_length=20),
        ),
    ]
