# Generated by Django 2.0 on 2018-11-20 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fixture', '0003_auto_20181115_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_operation', to='fixture.Machine'),
        ),
    ]
